In [1]:
import os
import cv2
import easygui as e
import numpy as np
from PIL import Image
import pickle

In [2]:
face_dict={}
path=r"D:\Projects\face-detection"
name=""
names=[]

In [3]:
class generate_dataset():
    def init():
        global path
        global names
        names=e.enterbox(msg="Name of the person",title="",default="",strip=True)
        try:
            os.mkdir(path+"\\"+"dataset")
        except FileExistsError:
            pass
        try:
            os.mkdir(path+"\\"+"dataset"+"\\"+names)
        except:
            pass
        
        new_path=path+"\\"+"dataset"+"\\"+names
        
        total_images=int(e.enterbox(msg="Number of images for training",title="",default="",strip=True))
        cam=cv2.VideoCapture(0)
        print("initializing camera")
        #command to make comparison with existing dataset i.e. face.xml
        #detector=cv2.CascadeClassifier("D:\\python\\face recognition\\face.xml")
        detector = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
        offset=50
        i=0
        while(1):
            ret,im=cam.read()
            #gray=cv2.cvtcolor(im,cv2.COLOR_BGR2GRAY)
            gray=cv2.cvtColor(im,cv2.COLOR_BGR2GRAY)
            print("gray",gray)
            faces=detector.detectMultiScale(gray,scaleFactor=1.1,minNeighbors=5,minSize=(30,30),flags=cv2.CASCADE_SCALE_IMAGE)
            for(x,y,w,h) in faces:
                i=i+1
                print("first_i",i)
                print("Image Saved")
                cv2.imwrite(new_path+"\\__"+name+"."+str(i)+".jpg",gray[y-offset:y+h+offset,x-offset:x+w+offset])
                cv2.rectangle(im,(x-50,y-50),(x+w+50,y+h+50),(225,0,0),2)
                cv2.putText(im,name+" "+str(i)+"/"+str(total_images),(x-45,y+h+45),cv2.FONT_HERSHEY_SIMPLEX,0.5,(255,255,0),2)
                cv2.putText(im,"press esc to exit",(x-45,y-40),cv2.FONT_HERSHEY_SIMPLEX,0.5,(255,255,0),2)
                print("iiiiiiiii=",i)
            try:
                cv2.imshow("dataset generation start",im)
            except:
                continue
            #print("jjjjjjjjjjjjj")
            k=cv2.waitKey(100) & 0xff
            #print("kkkkkkkkkk",k)
            if k==27:
                print("kkkkkkkkkkkkk",k)
                break
            if i+1>total_images:
                break
        cam.release()
        cv2.destroyAllWindows()

In [4]:
generate_dataset.init()

initializing camera
gray [[124 125 126 ... 113 113 115]
 [123 125 125 ... 112 112 113]
 [122 125 124 ... 109 110 112]
 ...
 [136 136 135 ... 112 115 117]
 [136 136 134 ... 112 113 116]
 [135 134 132 ... 112 113 114]]
gray [[119 119 120 ... 111 112 111]
 [119 118 118 ... 111 110 110]
 [121 118 118 ... 110 109 109]
 ...
 [126 129 129 ... 111 114 115]
 [129 127 125 ... 113 114 114]
 [129 126 123 ... 113 115 112]]
gray [[123 123 123 ... 110 110 109]
 [124 125 123 ... 109 109 112]
 [120 123 124 ... 108 108 110]
 ...
 [130 128 128 ... 110 108 108]
 [129 126 121 ... 108 108 110]
 [130 126 121 ... 109 109 110]]
first_i 1
Image Saved
iiiiiiiii= 1
gray [[119 121 121 ... 111 111 108]
 [119 120 121 ... 111 108 107]
 [119 120 123 ... 111 108 109]
 ...
 [133 129 127 ... 111 114 115]
 [130 127 123 ... 112 114 112]
 [129 126 122 ... 114 115 114]]
gray [[120 120 120 ... 112 113 111]
 [120 120 120 ... 112 114 111]
 [117 117 120 ... 115 117 114]
 ...
 [131 131 128 ... 112 106 106]
 [127 130 129 ... 109 1

first_i 27
Image Saved
iiiiiiiii= 27
gray [[123 124 124 ... 114 114 115]
 [122 123 124 ... 113 115 114]
 [122 123 124 ... 113 115 114]
 ...
 [136 134 133 ... 101 101  99]
 [136 136 135 ... 103 103  99]
 [136 136 135 ... 103 102  99]]
first_i 28
Image Saved
iiiiiiiii= 28
gray [[124 124 124 ... 114 115 113]
 [124 124 124 ... 113 114 114]
 [123 123 123 ... 111 114 114]
 ...
 [134 133 131 ...  94  91  94]
 [131 131 130 ...  99  91  92]
 [130 130 129 ... 101  97  95]]
first_i 29
Image Saved
iiiiiiiii= 29
gray [[123 121 120 ... 112 112 112]
 [121 121 121 ... 112 112 112]
 [120 123 123 ... 109 111 112]
 ...
 [131 130 131 ...  97  94  93]
 [131 131 131 ...  98  96  94]
 [134 132 131 ...  97  97  96]]
first_i 30
Image Saved
iiiiiiiii= 30
gray [[123 124 125 ... 112 113 114]
 [123 123 126 ... 113 113 113]
 [125 125 125 ... 115 115 113]
 ...
 [135 135 131 ...  97  95  97]
 [130 131 130 ... 100  97  96]
 [133 131 129 ... 100  98  96]]
first_i 31
Image Saved
iiiiiiiii= 31
gray [[124 124 124 ... 111 