In [3]:
import os
import cv2
import easygui as e
import numpy as np
from PIL import Image
import pickle

In [4]:
face_dict={}
path=r"D:\Projects\face-detection"
name=""
names=[]
class generate_dataset():
    def init():
        global path
        global names
        names=e.enterbox(msg="Name of the person",title="")
        try:
            os.mkdir(path+"\\"+"dataset")
        except FileExistsError:
            pass
        
        try:
            os.mkdir(path+"\\"+"dataset"+"\\"+names)
        except:
            pass
        
        new_path=path+"\\"+"dataset"+"\\"+names
        
        total_images=int(e.enterbox("msg=Number of images for training"))
        
        cam=cv2.VideoCapture(0)
        
        print("starting the camera")
        
        detector=cv2.CascadeClassifier(r"D:\Projects\face-detection\face.xml")
        
        offset=50
        i=0
        
        while(1):
            ret,im=cam.read()
            gray=cv2.cvtColor(im,cv2.COLOR_BGR2GRAY)
            print("gray",gray)
            
            faces=detector.detectMultiScale(gray,scaleFactor=1.1,minNeighbors=5,minSize=(30,30),flags=cv2.CASCADE_SCALE_IMAGE)
            
            for(x,y,w,h) in faces:
                i=i+1
                print(i)
                print("Image Saved")
                cv2.imwrite(new_path+"\\_"+name+"."+str(i)+".jpg",gray[y-offset:y+h+offset,x-offset:x+w+offset])
                cv2.rectangle(im,(x-50,y-50),(x+w+50,y+h+50),(220,0,0),2)
                cv2.putText(im,name+" "+str(i)+"/"+str(total_images),(x-45,y+h+45),cv2.FONT_HERSHEY_SIMPLEX,0.5,(0,0,255),2)
                cv2.putText(im,"press ESC for exit",(x-45,y-45),cv2.FONT_HERSHEY_SIMPLEX,0.5,(0,255,255),2)
                print("i=",i)
            
            try:
                cv2.imshow("dataset generation start....",im)
            except:
                continue
            
            k=cv2.waitKey(100) & 0xff
            
            if k==27:
                break
            
            if i+1>total_images:
                break
        
        cam.release()
        cv2.destroyAllWindows()

generate_dataset.init()

starting the camera
gray [[161 164 164 ... 170 168 168]
 [164 165 165 ... 169 168 168]
 [165 164 165 ... 168 168 169]
 ...
 [149 147 146 ... 157 156 156]
 [148 147 144 ... 155 154 155]
 [148 148 146 ... 155 155 155]]
1
Image Saved
i= 1
gray [[164 164 164 ... 168 168 169]
 [164 164 164 ... 168 168 169]
 [164 164 164 ... 168 168 169]
 ...
 [147 147 146 ... 157 158 158]
 [147 146 147 ... 156 155 156]
 [146 146 147 ... 155 155 155]]
2
Image Saved
i= 2
gray [[165 165 164 ... 168 167 168]
 [165 164 163 ... 168 167 167]
 [165 164 163 ... 168 167 167]
 ...
 [148 148 146 ... 156 156 157]
 [146 148 148 ... 155 154 156]
 [146 146 147 ... 156 156 156]]
3
Image Saved
i= 3
gray [[164 164 164 ... 167 167 168]
 [164 164 164 ... 168 167 168]
 [164 163 163 ... 168 168 168]
 ...
 [148 148 147 ... 158 157 156]
 [146 146 147 ... 157 157 156]
 [146 146 148 ... 157 157 156]]
4
Image Saved
i= 4
gray [[164 163 162 ... 168 168 169]
 [164 163 163 ... 168 168 170]
 [163 163 163 ... 167 168 169]
 ...
 [148 149 148