In [22]:
import os
import cv2
import easygui as e
import numpy as np
from PIL import Image
import pickle

In [23]:
face_dict={}
path=r"D:\Projects\face-detection"
name=""
names=[]

In [24]:
def get_images_and_labels(path):
    '''TO GET IMAGES AND LABELS'''
    global face_dict
    # global path
    names = os.listdir(path+"\\"+"dataset")
    image_paths = []
    new_path = path+"\\"+"dataset"
    for name in names:
        image_paths.append([os.path.join(new_path+"\\"+name, f) for f in os.listdir(new_path+"\\"+name)])
    
 # images will contains face images
    images = []
 # labels will contains the label that is assigned to the image
    labels = []
    i = 0
    j = 0
    for name in names:
        for image_path in image_paths[j]:
             # Read the image and convert to grayscale
            image_pil = Image.open(image_path).convert('L')
             # Convert the image format into numpy array
            image = np.array(image_pil, 'uint8')
             # Get the label of the image
            face_dict[j] = name

            faceCascade = cv2.CascadeClassifier(r"D:\Projects\face-detection\face.xml")
            #faceCascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
            print("**************************************")
            faces = faceCascade.detectMultiScale(image)
            print(faces)
             # If face is detected, append the face to images and the label to labels
            for (x, y, w, h) in faces:
                images.append(image[y: y + h, x: x + w])
                labels.append(j)
                cv2.imshow("Adding faces to traning set...", image[y: y + h, x: x + w])
                cv2.waitKey(10)
            i = i+1
        j = j+1
         # return the images list and labels list
    return images, labels

In [25]:
def save_obj(obj, name ):
    '''TO SAVE THE OBJECT OF TRAINED FILE'''
    with open(name + '.pkl', 'wb') as f:
        pickle.dump(obj, f, pickle.HIGHEST_PROTOCOL)

In [26]:
class train:
    def init():
        global path
        global face_dict
        #recognizer=cv2.face.LBPHFaceRecognizer_create()
        recognizer=cv2.face.LBPHFaceRecognizer.create()
        print(path)
        #recognizer.read(path+"\\trainer.yml")
        images,labels=get_images_and_labels(path)
        save_obj(face_dict,path+"\\trained_faces.pkl")
        recognizer.train(images,np.array(labels))
        recognizer.save(path+"\\trainer.yml")
        print("TRAINED",face_dict)
        cv2.destroyAllWindows()

In [27]:
get_images_and_labels(path)

**************************************
[[ 91 161  60  60]]
**************************************
[[ 58  43 182 182]]
**************************************
[[ 50  33 194 194]]
**************************************
[[ 49  51 187 187]]
**************************************
[[ 49  46 165 165]]
**************************************
[[ 55  55 178 178]]
**************************************
[[ 47  47 191 191]]
**************************************
[[ 49  50 188 188]]
**************************************
[[ 51  51 189 189]]
**************************************
[[ 53  52 183 183]]
**************************************
[[ 50  53 186 186]]
**************************************
[[ 48  51 174 174]]
**************************************
[[ 51  51 193 193]]
**************************************
[[ 49  47 193 193]]
**************************************
[[ 51  50 189 189]]
**************************************
[[ 50  48 189 189]]
**************************************
[[ 46  48 203 203

([array([[128, 126, 123, ...,  85,  88,  91],
         [131, 127, 122, ...,  87,  88,  89],
         [131, 127, 122, ...,  87,  87,  86],
         ...,
         [117, 116, 117, ...,  81,  80,  81],
         [116, 115, 116, ...,  81,  80,  81],
         [115, 116, 117, ...,  82,  85,  87]], dtype=uint8),
  array([[100, 100, 100, ..., 163, 162, 163],
         [100, 101, 102, ..., 163, 162, 161],
         [103, 102, 100, ..., 164, 163, 162],
         ...,
         [ 39,  42,  44, ..., 215, 214, 213],
         [ 40,  42,  43, ..., 214, 215, 213],
         [ 39,  43,  44, ..., 213, 214, 214]], dtype=uint8),
  array([[192, 187, 182, ..., 161, 161, 161],
         [190, 186, 182, ..., 162, 162, 162],
         [184, 183, 181, ..., 163, 163, 162],
         ...,
         [ 47,  43,  39, ..., 208, 208, 208],
         [ 47,  43,  40, ..., 208, 208, 208],
         [ 47,  45,  41, ..., 208, 209, 209]], dtype=uint8),
  array([[188, 188, 190, ..., 160, 158, 157],
         [189, 189, 191, ..., 159, 158,

In [28]:
train.init()

D:\Projects\face-detection
**************************************
[[ 91 161  60  60]]
**************************************
[[ 58  43 182 182]]
**************************************
[[ 50  33 194 194]]
**************************************
[[ 49  51 187 187]]
**************************************
[[ 49  46 165 165]]
**************************************
[[ 55  55 178 178]]
**************************************
[[ 47  47 191 191]]
**************************************
[[ 49  50 188 188]]
**************************************
[[ 51  51 189 189]]
**************************************
[[ 53  52 183 183]]
**************************************
[[ 50  53 186 186]]
**************************************
[[ 48  51 174 174]]
**************************************
[[ 51  51 193 193]]
**************************************
[[ 49  47 193 193]]
**************************************
[[ 51  50 189 189]]
**************************************
[[ 50  48 189 189]]
*****************************